---
- name: Dispatch AAP Configuration as Code
  ansible.builtin.include_role:
    name: infra.aap_configuration.dispatch
  vars:
    aap_configuration_async_delay: 0
    aap_configuration_async_retries: 1
